### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G5_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by IgorWitt** [comment]
Software voltado para idosos aprenderem a mexer no computador, realizando pesquisas e vídeos. Com o objetivo de ser fácil, educativo, e prático para o idoso se familiarizar com a tecnologia.

**Comment by Alan-fernando** [comment]
software para pessoas que possuam alguma deficiência ou dificuldade, onde com um comando de voz o computador apresentará oque o usuário precisa de forma fácil e rápida.

EX:
usuário: abrir facebook.
software: ira abrir o facebook se já instalado no computador ou irá fazer a pesquisa dele no navegador se ainda não isntalado.

OU

usuário: me ajude a configurar o tamanho da fonte do meu computador .
software: gostaria que eu fizesse automaticamente ou lhe mostre passo a passo.

se o usuário escolher que faça a mudança automaticamente ele só ira precisar informar o tamanho da fonte, ou se ele optar para que lhe mostre e ensine , o software ira mostrar passo a passo para ele.

**Comment by gabrielReisPR** [comment]
software que identifica os sinais neurais de porcos em sua morte e verifica se foi um abate sem dor

**Comment by gabrielReisPR** [comment]
drone em forma de pássaro que o pessoal vai poder monitorar  o inimigo

**Comment by gabrielReisPR** [comment]
software que identifica os latidos dos cachorres e verifica se ele esta precisando de algo

**Comment by gabrielReisPR** [comment]
software que ao identificar como esta sua postura e corrige a mesma

**Comment by Alan-fernando** [comment]
software para aviários  onde ira identificar o ambiente as condições e os alimentos  para que estejam confortável e propícios para as aves

**Comment by BolzanBug** [comment]
Um software para cadastrar e localizar eventos de uma cidade, seja quando acontece eventos regionais, eventos culturais, festas e baladas disponíveis para todo o público, ou pela venda de ingressos

**Comment by BolzanBug** [comment]
Um software que detecta e reporta problemas nas estradas, seja por enchentes, desmoronamentos, acidentes entre motoristas, que tenha disponibilidade de reportar o problema para a prefeitura e em casos de acidentes graves contatar os hospitais

**Comment by IgorWitt** [comment]
Software para prestar e receber carona, somente com a comunidade universitária. Voltado para os alunos que dependem de carona para chegar na faculdade.

**Comment by BolzanBug** [comment]
um aplicativo para cadastrar datas e eventos agendados de uma pessoa, podendo programar para diferentes atividades como: lembrar de quando precisa fazer a revisão de alguma parte específica do carro(com possibilidade de ativar uma "repetição", para fazer em determinados intervalos de tempo), ou fazer um cronograma do dia, mostrando os horários "livres" para fazer outras atividades

**Comment by Alan-fernando** [comment]
Software de gestão financeira pessoal, onde iria rastrear todos os gastos mensal do usuário e trazer todo final de mês insights financeiros, onde o usuário poderia ter uma melhor visão de como investir seu dinheiro de maneira certa e rendeira no próximo.
