### ISSUE TITLE
Mapa de stakeholders

### ISSUE THREAD

**Issue by gabrielReisPR** [radamesp7/AbexII_G5_2024#2]
Escrevam os principais impactados pelo software(ambiente interno, ambiente externo, macroambiente)

**Comment by BolzanBug** [comment]
Link com o documento do Canva para usa de base:
[https://www.canva.com/design/DAGOnsUeyKE/NjwkiwUx1v479pCy4-S3Hw/edit?utm_content=DAGOnsUeyKE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)

**Comment by BolzanBug** [comment]
Eu (Gabriel Bolzan) e o Gabriel dos Reis atualizamos o documento no canva , preenchemos todo o mapa dos StakeHolders
