### ISSUE TITLE
Mapa de Observações

### ISSUE THREAD

**Issue by BolzanBug** [radamesp7/AbexII_G5_2024#3]
Fazer um mapa de observações(Conhecer quais as necessidades dos Stakeholders - Foco no Usuário), por enquanto ir colocando as informações no link do Canva abaixo:
[Link Canva](https://www.canva.com/design/DAGOnlb9csk/wbNL_t-mIpPxXg0fJmM84Q/edit?utm_content=DAGOnlb9csk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
Depois desenvolver o "Mapa de Observação" no Wiki do repositório da ABEX II, como ítem 2 da página "Design Thinking".

O documento em anexo é para ajudar a fazer o Mapa de Observações
[Observações.pdf](https://github.com/user-attachments/files/16719947/Observacoes.pdf)

NOTA: Detalhar aqui no github o que foi modificado no documento

**Comment by BolzanBug** [comment]
se quiserem detalhar aqui as observações podem, mas deixem formatado claramente para saber o que é cada coisa

**Comment by BolzanBug** [comment]
Problemas:
- Navegação do aplicativo
- Informações Desatualizadas

Padrões:
- Padronizar icones e cores de botões, a fim de ficar mais interativo

**Comment by GustavoH3** [comment]
Necessidades:
- Interface intuitiva;
- Facilidade no acesso;
- Conteúdo relevante e adaptado;

Restrições:
- 

Dificuldades:
- Download e atualizações;
- Feedback do usuário;

Padrões:
- Design;

Adaptações:
- Assistente de voz;
- Botões de acessibilidade;
- Paleta de cores;

Problemas:
- Atualização do conteúdo;
- Navegação no aplicativo;
